version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
      - DJANGO_SETTINGS_MODULE=config.settings.dev
