version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
      - DJANGO_SETTINGS_MODULE=config.settings.dev

  redis:
    image: redis
    ports:
      - 6379:6379

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
