# Generated by Django 4.0 on 2021-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='фамилия'),
        ),
    ]
